cabal-version:   3.0
name:            corbenic-site
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

flag dev
  description: Be less pedantic for rapid rebuilds
  default: False
  manual: True

common shared-config
    default-language: GHC2024
    if !flag(dev)
      ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror
    default-extensions:
        OverloadedStrings
    build-depends:
        base >= 4.14 && < 5,
        text,
        corbenic-prelude
    mixins:
        base hiding (Prelude)

executable site
    import:           shared-config
    main-is:          site.hs
    hs-source-dirs:   .
    ghc-options:      -threaded
    build-depends:    hakyll
                    , typed-process
                    , bytestring
