cabal-version:   3.0
name:            corbenic-lang
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

flag dev
  description: Be less pedantic for rapid rebuilds
  default: False
  manual: True

common shared-config
    default-language: GHC2024
    if !flag(dev)
      ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror
    default-extensions:
        OverloadedStrings
        TemplateHaskell
        TypeFamilies
        PatternSynonyms
        ViewPatterns
    build-depends:
        base >= 4.14 && < 5,
        relude,
        text,
        lens,
        QuickCheck
    mixins:
        base hiding (Prelude)

library
    import:           shared-config
    hs-source-dirs:   src
    build-depends:    array
                    , ansi-terminal
                    , mtl
                    , containers
                    , corbenic-prelude
    exposed-modules:   Frontend.Diagnostics
                     , Frontend.Lexer
                     , Frontend.Lexer.Tokenizers
                     , Frontend.Lexer.Types
                     , Frontend.IOPipeline
                     , Syntax.Chars
                     , Syntax.Documentation
                     , Syntax.Fixity
                     , Syntax.Identifier
                     , Syntax.Literal
                     , Syntax.Location
                     , Syntax.Token


test-suite test-corbenic
    import:           shared-config
    type:             exitcode-stdio-1.0
    main-is:          Tests.hs
    hs-source-dirs:   test
    other-modules:    Tests.Lexer
    build-depends:    corbenic-lang
                    , corbenic-prelude
                    , tasty
                    , tasty-hunit
                    , tasty-quickcheck
                    , containers
